# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

binom_pmf <- function(k, n, p) {
    .Call('_Hotspot_binom_pmf', PACKAGE = 'Hotspot', k, n, p)
}

norm_sf <- function(x, mu, std) {
    .Call('_Hotspot_norm_sf', PACKAGE = 'Hotspot', x, mu, std)
}

dist_params_mu <- function(mu, sd, N) {
    .Call('_Hotspot_dist_params_mu', PACKAGE = 'Hotspot', mu, sd, N)
}

dist_params_sd <- function(mu, sd, N) {
    .Call('_Hotspot_dist_params_sd', PACKAGE = 'Hotspot', mu, sd, N)
}

nonzero_mean <- function(arr) {
    .Call('_Hotspot_nonzero_mean', PACKAGE = 'Hotspot', arr)
}

nonzero_std <- function(arr, mu) {
    .Call('_Hotspot_nonzero_std', PACKAGE = 'Hotspot', arr, mu)
}

gi_significance <- function(gi, logexp, counts, neighbors, umis) {
    .Call('_Hotspot_gi_significance', PACKAGE = 'Hotspot', gi, logexp, counts, neighbors, umis)
}

gi_significance_all <- function(gi, logexp, counts, neighbors, umis) {
    .Call('_Hotspot_gi_significance_all', PACKAGE = 'Hotspot', gi, logexp, counts, neighbors, umis)
}

